### ISSUE TITLE
:white_check_mark: Input 모바일 버전 뒤로가기 버튼 추가 // 애니메이션 적용

### ISSUE THREAD

**Issue by wooleejaan** [codeit-bootcamp-frontend/0-the-julge-young-developers#113]
### Description

뒤로 가기 버튼 추가하기 및 애니메이션 적용

### To-do

- [x] 뒤로 가기 버튼 추가 
- [x] 뒤로 가기 기능 추가 (뒤로 가기 시 상태 기억)
- [x] 모달 클릭 시 fadeIn 애니메이션 추가 
- [x] 다음 버튼 클릭 시 슬라이드 애니메이션 추가
