### ISSUE TITLE
:white_check_mark: 사장님 페이지 - 공고 등록하기

### ISSUE THREAD

**Issue by shyjnnn** [codeit-bootcamp-frontend/0-the-julge-young-developers#126]
### Description

공고 등록하기 모달 구현

### To-do

- [ ] 공고 등록 api
- [ ] 공고 가져오기 api
- [ ] 공고 등록 interface pc
- [ ] 공고 등록 interface funnel(mobile)
- [ ] 공고 카드 리스트 interface
