### ISSUE TITLE
:white_check_mark: 알바님 공고 상세 페이지 - userId 쿠키를 받아 처리

### ISSUE THREAD

**Issue by hayoung-99** [codeit-bootcamp-frontend/0-the-julge-young-developers#129]
### Description
쿠키에 저장된 userId를 이용해 
현재 유저가 해당 공고를 신청/미신청/또는 close 여부에 따라 조건부 렌더링 작업

### To-do
- [x] 쿠키로 userId 받는 거 테스트하기 (이후 mock 데이터로 만들어서 사용할 듯)
- [x] 알바님/사장님 인지에 따라 분기 처리하기
- [x] 알바님인 경우, 해당 공고 마감 여부에 따라 신청 막기
- [x] 알바님인 경우, 해당 공고 신청/미신청 여부에 따라 신청 막기
