### ISSUE TITLE
:white_check_mark: 맞춤 공고 데이터 불러오는 로직 구현

### ISSUE THREAD

**Issue by Andy-Shin99** [codeit-bootcamp-frontend/0-the-julge-young-developers#130]
### Description

맞춤 공고 컴포넌트에 조건 별 데이터를 불러오는 로직을 구현합니다.

### To-do

- [ ] 로그인이 되어 있다면 맞춤 공고를 보여줍니다. (로그인 X -> 맞춤 공고 렌더링 X)
- [ ] User Type을 확인하여
  - [ ] 알바일 경우 : user_id를 불러와서 -> GET /users/{user_id}로 API 요청 -> 선호지역을 가져 온 후(선호 지역이 어떤 형식으로 들어가 있는지 확인 필요, API 요청에 필요한 형태로 되어 있지 않으면 포맷팅 해야 함) -> 해당 선호지역에 해당하는 API GET 요청 -> 데이터 바탕으로 렌더링합니다
  - [ ] 사장일 경우 : 그냥 아무 데이터 3개를 보여줍니다.
