### ISSUE TITLE
:white_check_mark: 공통 컴포넌트 제작 - GNB UI

### ISSUE THREAD

**Issue by Andy-Shin99** [codeit-bootcamp-frontend/0-the-julge-young-developers#15]
### Description

GNB 컴포넌트의 UI를 제작합니다.

### To-do

- [ ] GNB 컴포넌트 제작
  - [ ] Logo 컴포넌트 구현
  - [ ] SearchBar 컴포넌트 구현
  - [ ] Button 컴포넌트 구현 -> 각 로그인 / 회원가입 / 내 가게로 재사용
  - [ ]  notification 버튼은 구현 X
- [ ] 반응형 스타일 구현
  - [ ] PC
  - [ ] Tablet
  - [ ] Mobile
