### ISSUE TITLE
:white_check_mark: GNB 유저 타입 확인 기능 추가

### ISSUE THREAD

**Issue by Andy-Shin99** [codeit-bootcamp-frontend/0-the-julge-young-developers#158]
### Description

GNB에서 유저 타입을 확인하여 서로 다른 버튼을 렌더링 하고, 사장일 경우 storeId를 쿠키에 저장합니다.

### To-do

- [x] 로그인 여부를 확인합니다.
  - [x] 로그인이 안 되었을 경우 로그인 / 회원가입 버튼을 렌더링 합니다.
- [ ] 로그인이 되었을 경우
  - [ ] 사장님 : 내 가게와 알림 버튼을 렌더링 합니다
  - [ ] 사장님 : storeId를 받아와 쿠키에 저장합니다.
  - [ ] 알바님 : 내 프로필과 알림 버튼을 렌더링 합니다.
