### ISSUE TITLE
:white_check_mark: 공통 컴포넌트 제작 - 공고 목록/상세 페이지 카드 컴포넌트 (태블릿/모바일 반응형 추가) 

### ISSUE THREAD

**Issue by wooleejaan** [codeit-bootcamp-frontend/0-the-julge-young-developers#16]
### Description

제작한 카드 컴포넌트에 태블릿/모바일 반응형을 추가합니다. 

### To-do

- [x] 태블릿 반응형 추가 
  - [x] 상세 페이지 카드 컴포넌트 반응형
  - [x] 공고 목록 컴포넌트 반응형 
- [x] 모바일 반응형 추가 
  - [x] 상세 페이지 카드 컴포넌트 반응형
  - [x] 공고 목록 컴포넌트 반응형
