### ISSUE TITLE
:bug: 사장님 페이지 - 무한 스크롤 및 funnel 수정

### ISSUE THREAD

**Issue by shyjnnn** [codeit-bootcamp-frontend/0-the-julge-young-developers#186]
### Description
무한 스크롤 안되는 현상, funnel에서 버튼 활성화,비활성화 안되는 버그 해결

### To-do

- [x] #200

공고 모달
- [x] 시급 undefined 현상 해결
- [x] 날짜 선택 오늘 이전 불가능 하도록 수정

 funnel일 때, 
- [ ] input에 값이 없으면 버튼 비활성화
    - [ ] input 수정 후 값이 없어지면 역시 버튼 비활성화
- [ ] input에 default value 있으면 버튼 활성화
