### ISSUE TITLE
:bug: 사장님 페이지 가게 상세 버그 수정

### ISSUE THREAD

**Issue by shyjnnn** [codeit-bootcamp-frontend/0-the-julge-young-developers#190]
### Description
- 가게 등록 -> 성공 시, 모달 안닫힘, 성공 여부 안보여짐
- 등록한 공고 없을 때 무한 로딩 발생
- 사장님 페이지 (my-shop)을 알바생일때 들어오지 못하도록 수정

### To-do
- [x] 가게 등록 -> 성공 시, 모달 안닫힘, 성공 여부 안보여짐
- [x] 등록한 공고 없을 때 무한 로딩 발생
- [x] 사장님 페이지 (my-shop)을 알바생일때 들어오지 못하도록 수정
