### ISSUE TITLE
:white_check_mark: Gnb feature 만들기

### ISSUE THREAD

**Issue by Andy-Shin99** [codeit-bootcamp-frontend/0-the-julge-young-developers#41]
### Description

Gnb feature 만들기

### To-do

- [ ] isLogin 상태 정의
- [ ] hasNotification 상태 정의
- [ ] 각 click 이벤트 handler 함수 정의
- [ ] UiGnb 불러와서 prop으로 내려주기
