### ISSUE TITLE
:white_check_mark: 페이지 개발 초기 셋팅 - cookie package / page folder / Context api 

### ISSUE THREAD

**Issue by wooleejaan** [codeit-bootcamp-frontend/0-the-julge-young-developers#49]
### Description

페이지 폴더 / 쿠키 및 Context api 초기 셋팅 및 로직 완성 

### To-do

- [x] 페이지 폴더 제작  
- [x] 쿠키 패키지 설치 
- [x] Authorization에 쿠키 주입 
- [x] Context api 세팅
