### ISSUE TITLE
:white_check_mark: 공통 컴포넌트 제작 - 공고 목록 

### ISSUE THREAD

**Issue by wooleejaan** [codeit-bootcamp-frontend/0-the-julge-young-developers#5]
### Description

공통 컴포넌트(공고 목록) 제작 

### To-do

- [x] card-list
  - [x] ui-notice-list : 최근에 본 공고, 맞춤 공고, 전체 공고, 검색어에 대한 공고 목록
  - [ ] ui-list-order-select : 필터 순서 
- [x] card 
  - [x] ui-notice-card : 공고 목록에 들어갈 카드들 
  - [x] ui-notice-card-chip : 기존 시급보다 100% up - 모바일에서 변경되므로
  - [x] ui-shop-card : 사장님/알바님 공고 상세
