### ISSUE TITLE
✅ 공통 컴포넌트 제작 - 레이아웃, 모달, 토스트, 알림창, 상세 필터

### ISSUE THREAD

**Issue by hayoung-99** [codeit-bootcamp-frontend/0-the-julge-young-developers#6]
### Description
여러 페이지에 공통으로 사용할 수 있는 모달, 토스트, 알림창, 상세 필터 등의 UI를 제작

### To-do
- [x] 도메인 공통 레이아웃 (common-layout)
- [x] 모달 (common-modal)
- [x] 토스트 (common-toast)
- [x] 알림창 (dropdown-modal-layout)
- [x] 상세필터 (filter)
