### ISSUE TITLE
:bug: 공통 컴포넌트 - input 과 select 분리, d.ts 파일 ts로 변경

### ISSUE THREAD

**Issue by shyjnnn** [codeit-bootcamp-frontend/0-the-julge-young-developers#60]
### Description
select 타입 추가로 인해 복잡성이 늘어나 input과 select를 분리하기로 결정했습니다.
d.ts 파일 ts로 변경 작업도 함께 할 예정입니다.

### To-do

- [ ] input 과 select 분리
- [ ] d.ts 파일 ts로 변경
- [ ] select title 없고, default 있고, 색상 없는 타입 추가
