### ISSUE TITLE
:white_check_mark: 알바 페이지 조립 및 기타 - Input 레이아웃 구성 및 미디어쿼리 훅 제작 / 그외 기타 api 보충 작업 

### ISSUE THREAD

**Issue by wooleejaan** [codeit-bootcamp-frontend/0-the-julge-young-developers#65]
### Description

알바님 페이지 (내 프로필 도메인 개발)

### To-do

- [x] api 수정 
  - [x] 유저 데이터 bio 부분 수정 
  - [x] 로딩 처리 예시 jsdoc에 추가 
- [ ] Input 모달 관련 (funnel) 
  - [ ] UiBgGrayModal 수정 
  - [x] 미디어 쿼리 훅 추가 
  - [ ] 퍼널을 위한 상태 관리 추가
