### ISSUE TITLE
:white_check_mark: 컴포넌트 제작 - Footer

### ISSUE THREAD

**Issue by Andy-Shin99** [codeit-bootcamp-frontend/0-the-julge-young-developers#7]
### Description

Footer 컴포넌트 제작

### To-do

- [ ] Copyright
- [ ] Privacy Policy, FAQ 링크
  - [ ] 루트 페이지 연결로 구현 
- [ ] Social 링크 연결
  - [ ] 각 서비스 페이지 연결로 구현
  - [ ] 이메일은 루트 페이지 연결
